# Generated by Django 4.2.17 on 2024-12-31 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT')], max_length=10)),
                ('app_id', models.CharField(max_length=200, null=True)),
                ('app_sectet', models.UUIDField(null=True)),
                ('content_type', models.CharField(max_length=50, null=True)),
                ('accept', models.CharField(max_length=5, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='Account.accountmodel')),
            ],
        ),
    ]
